sources:
  - name: gnars
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/84925/gnars-mainnet/version/latest
        retry: 2
documents:
  - './src/queries/**/*.graphql'