sources:
  - name: gnars
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clwh32mvalyh201vi1ck71seq/subgraphs/gnars-mainnet/latest/gn
        retry: 2
documents:
  - './src/queries/**/*.graphql'