sources:
  - name: gnars
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_clwh32mvalyh201vi1ck71seq/subgraphs/gnars-mainnet/latest/gn
    transforms:
      - blockTracking:
          validateSchema: true
  # - name: nouns
  #   handler:
  #     graphql:
  #       endpoint: https://api.thegraph.com/subgraphs/name/nounsdao/nouns-subgraph
documents:
  - "./queries/**/*.graphql"
plugins:
  - pollingLive:
      defaultInterval: 12_000
additionalResolvers:
  - "./queries/resolvers"
